spring.application.name=chat-backend

# Certificate Properties app.cert.*
app.cert.ca-cert-path=certs/ca.crt
app.cert.ca-key-path=certs/ca-private.pem
app.cert.im-cert-path=certs/im.crt
app.cert.im-key-path=certs/im-private.pem

app.cert.output-dir=certs

app.cert.key-size=4096

# Sertifikat traje 10 godina 3650 dana
app.cert.ca-valid-duration=3650
app.cert.im-valid-duration=365

# Issuer CA
app.cert.ca-dn.common-name=Singidunum CA
app.cert.ca-dn.org-unit=KIBP
app.cert.ca-dn.org=Singidunum
app.cert.ca-dn.locality=Belgrade
app.cert.ca-dn.state=RS
app.cert.ca-dn.country=RS

# Issuer Intermediate
app.cert.im-dn.common-name=Singidunum Intermediate
app.cert.im-dn.org-unit=KIBP
app.cert.im-dn.org=Singidunum
app.cert.im-dn.locality=Belgrade
app.cert.im-dn.state=RS
app.cert.im-dn.country=RS

